// viz/app/linker_page/blend.js
//
// The LEARNED BLEND that augments the deterministic scorer. Two pieces:
//   extractBlendFeatures(ctx, candidate, opts) — the feature vector (the full
//     deterministic score `logDet` PLUS decomposed sub-factors PLUS embed_cosine).
//   blendScore(features, weights)             — calibrated probability (logistic).
//
// SINGLE SOURCE OF TRUTH: both the live ranker (recommendSimilar) and the offline
// trainer/eval (tools/linker_ml/*) import THIS module, so they can never drift. The
// weights live in ./blend_weights.js (committed, generated by
// tools/linker_ml/make_blend_weights.mjs). The embedding cosine is optional: pass
// opts.embedCosFn only when a vectors file is loaded (see ./embeddings.js); otherwise
// embed_cosine is 0 and the no-embed weight set must be used (correct calibration).
//
// extractBlendFeatures reuses the already-built per-anchor `ctx` (from
// prepScorePairCtx) for the A side and computes the B side fresh — identical values to
// tools/linker_ml/featurize.mjs's reference implementation. detScore is passed in by the
// caller (which already computed scorePairWithVocab) to avoid a circular import.

import { tokenizeQuery, normSearchText } from "../sku.js";
import {
	filterSimTokens,
	tokenContainmentScore,
	extractAbv,
	abvMultiplier,
	extractAgeFromText,
	bareAgeCandidates,
	extractEditionCodes,
	editionCodeMultiplier,
} from "./similarity.js";
import { conceptConflictMultiplier } from "./concepts.js";
import { DISTINCTIVE_IDF } from "./vocab.js";

// Ordered feature columns. The weights file carries its own `keys` (a subset when the
// no-embed model is used), so blendScore is robust to which set is shipped.
export const FEATURE_KEYS = [
	"logDet",
	"contain",
	"woScore",
	"woShared",
	"topTermShared",
	"tgtCov",
	"candExtra",
	"gradedCov",
	"sizePen",
	"pricePen",
	"ageRel",
	"ageOneSided",
	"abvMult",
	"abvBoth",
	"edMult",
	"edBoth",
	"smwsShared",
	"conceptMult",
	"storeShared",
	"badSku",
	"sharedTok",
	"jacc",
	"minTok",
	"maxTok",
	"lenDiff",
	"embedCos",
];

function isBadSkuLite(sku) {
	const s = String(sku || "").toLowerCase();
	if (!s) return true;
	return s.startsWith("u:") || s.startsWith("id:") || s.startsWith("upc:") || s === "unknown";
}

// ctx = prepScorePairCtx(anchor); candidate = the aggregate being scored.
// opts = { vocab, sizePenaltyFn, pricePenaltyFn, detScore, embedCosFn? }
export function extractBlendFeatures(ctx, candidate, opts) {
	const vocab = opts.vocab;
	const nameA = ctx.name || "";
	const nameB = candidate.name || "";
	const aSku = String(ctx.sku || "");
	const bSku = String(candidate.sku || "");

	const normB = normSearchText(nameB);
	const rawB = tokenizeQuery(normB);
	const fB = filterSimTokens(rawB);
	const fA = ctx.toks || [];
	const setA = new Set(fA);
	const setB = new Set(fB);

	let sharedTok = 0;
	for (const t of setA) if (setB.has(t)) sharedTok++;
	const unionTok = new Set([...setA, ...setB]).size || 1;

	const contain = tokenContainmentScore(ctx.rawToks, rawB);
	const wo = vocab.weightedOverlap(nameA, nameB);

	const distA = ctx.distinctiveTerms || new Set();
	const distB = vocab.distinctiveUnigramsForName(nameB) || new Set();
	const termsA = vocab.termsForName(nameA);
	const termsB = vocab.termsForName(nameB);

	let covM = 0;
	for (const t of distA) if (termsB.has(t)) covM++;
	const tgtCov = distA.size ? covM / distA.size : 1;
	let candExtra = 0;
	for (const t of distB) if (!termsA.has(t)) candExtra++;

	const uniA = ctx.allUnigrams || new Set();
	let interW = 0;
	let totalW = 0;
	for (const t of uniA) {
		const w = vocab.idf(t);
		totalW += w;
		if (termsB.has(t)) interW += w;
	}
	const gradedCov = totalW > 0 ? interW / totalW : 1;

	const topTerm = ctx.topTerm;
	const topTermShared = topTerm && topTerm.idf >= DISTINCTIVE_IDF && termsB.has(topTerm.term) ? 1 : 0;

	const sizePen = typeof opts.sizePenaltyFn === "function" ? opts.sizePenaltyFn(aSku, bSku) : 1;
	const pricePen = typeof opts.pricePenaltyFn === "function" ? opts.pricePenaltyFn(aSku, bSku) : 1;

	const ageA = ctx.age || "";
	const ageB = extractAgeFromText(normB);
	let ageRel = 0;
	if (ageA && ageB) ageRel = ageA === ageB ? 1 : -1;
	else if (ageA && !ageB && bareAgeCandidates(normB).has(ageA)) ageRel = 1;
	else if (ageB && !ageA && bareAgeCandidates(ctx.norm || "").has(ageB)) ageRel = 1;
	const ageOneSided = (ageA && !ageB) || (ageB && !ageA) ? 1 : 0;

	const abvA = ctx.abv;
	const abvB = extractAbv(normB);
	const abvMult = abvMultiplier(abvA, abvB);
	const abvBoth = abvA != null && abvB != null ? 1 : 0;

	const edA = ctx.editionCodes || new Set();
	const edB = extractEditionCodes(nameB) || new Set();
	const edMult = editionCodeMultiplier(edA, edB);
	let smwsShared = 0;
	for (const c of edA)
		if (c.startsWith("smws:") && edB.has(c)) {
			smwsShared = 1;
			break;
		}
	const edBoth = edA.size > 0 && edB.size > 0 ? 1 : 0;

	const conceptMult = conceptConflictMultiplier(nameA, nameB);

	const aStores = ctx.stores instanceof Set ? ctx.stores : new Set(ctx.stores || []);
	const bStores = candidate.stores;
	const bHas = bStores
		? typeof bStores.has === "function"
			? (x) => bStores.has(x)
			: (x) => bStores.includes(x)
		: () => false;
	let storeShared = 0;
	for (const s of aStores)
		if (bHas(s)) {
			storeShared = 1;
			break;
		}

	const badSku = isBadSkuLite(aSku) || isBadSkuLite(bSku) ? 1 : 0;
	const detScore = Number.isFinite(opts.detScore) ? opts.detScore : 0;
	const embedCos = typeof opts.embedCosFn === "function" ? opts.embedCosFn(aSku, bSku) : 0;

	return {
		logDet: Math.log1p(Math.max(0, detScore)),
		contain,
		woScore: wo.score,
		woShared: (wo.shared && wo.shared.length) || 0,
		topTermShared,
		tgtCov,
		candExtra,
		gradedCov,
		sizePen,
		pricePen,
		ageRel,
		ageOneSided,
		abvMult,
		abvBoth,
		edMult,
		edBoth,
		smwsShared,
		conceptMult,
		storeShared,
		badSku,
		sharedTok,
		jacc: sharedTok / unionTok,
		minTok: Math.min(fA.length, fB.length),
		maxTok: Math.max(fA.length, fB.length),
		lenDiff: Math.abs((ctx.norm || "").length - normB.length),
		embedCos,
	};
}

const sigmoid = (z) => (z >= 0 ? 1 / (1 + Math.exp(-z)) : Math.exp(z) / (1 + Math.exp(z)));

// weights = { keys, mean, std, w, b }. Returns a calibrated probability in [0,1].
export function blendScore(features, weights) {
	if (!weights || !weights.keys) return 0;
	let dot = weights.b;
	for (let j = 0; j < weights.keys.length; j++) {
		const v = Number(features[weights.keys[j]]);
		const z = ((Number.isFinite(v) ? v : 0) - weights.mean[j]) / (weights.std[j] || 1);
		dot += weights.w[j] * z;
	}
	return sigmoid(dot);
}
