// viz/app/linker_page/blend.js
//
// The LEARNED BLEND that augments the deterministic scorer. Two pieces:
//   extractBlendFeatures(ctx, candidate, opts) — the feature vector (the full
//     deterministic score `logDet` PLUS decomposed sub-factors PLUS embed_cosine).
//   blendScore(features, weights)             — calibrated probability (logistic).
//
// SINGLE SOURCE OF TRUTH: both the live ranker (recommendSimilar) and the offline
// trainer/eval (tools/linker_ml/*) import THIS module, so they can never drift. The
// weights live in ./blend_weights.js (committed, generated by
// tools/linker_ml/make_blend_weights.mjs). The embedding cosine is optional: pass
// opts.embedCosFn only when a vectors file is loaded (see ./embeddings.js); otherwise
// embed_cosine is 0 and the no-embed weight set must be used (correct calibration).
//
// extractBlendFeatures reuses the already-built per-anchor `ctx` (from
// prepScorePairCtx) for the A side and computes the B side fresh — identical values to
// tools/linker_ml/featurize.mjs's reference implementation. detScore is passed in by the
// caller (which already computed scorePairWithVocab) to avoid a circular import.

import { tokenizeQuery, normSearchText } from "../sku.js";
import {
	filterSimTokens,
	tokenContainmentScore,
	extractAbv,
	abvMultiplier,
	extractAgeFromText,
	bareAgeCandidates,
	extractEditionCodes,
	editionCodeMultiplier,
	levenshtein,
} from "./similarity.js";
import { conceptConflictMultiplier } from "./concepts.js";
import { DISTINCTIVE_IDF } from "./vocab.js";

// Ordered feature columns. The weights file carries its own `keys` (a subset when the
// no-embed model is used), so blendScore is robust to which set is shipped.
export const FEATURE_KEYS = [
	"logDet",
	"contain",
	"woScore",
	"woShared",
	"topTermShared",
	"tgtCov",
	"candExtra",
	"gradedCov",
	"sizePen",
	"pricePen",
	"ageRel",
	"ageOneSided",
	"abvMult",
	"abvBoth",
	"edMult",
	"edBoth",
	"smwsShared",
	"conceptMult",
	"storeShared",
	"badSku",
	"sharedTok",
	"jacc",
	"minTok",
	"maxTok",
	"lenDiff",
	"containGated",
	"grpStoreOverlap",
	"grpStoreCollideCount",
	"grpStoreJaccard",
	"grpSameSkuShare",
	"grpSizeConflict",
	"grpSizeJaccard",
	"grpAbvDiff",
	"grpAbvBoth",
	"grpYearDiff",
	"grpYearBoth",
	"grpPriceRatio",
	"grpCountA",
	"grpCountB",
	"crossEntityConflicts",
	"embedCos",
];

// NOTE (2026-06-04): a character-trigram cosine feature was prototyped here. On the
// transitive-grouping-BUGGY dataset it helped (+6.2 rec@99) by rescuing spelling-variant pairs
// the fragmentation had mislabeled. After the grouping fix, those pairs are correctly grouped as
// positives and the fine-tuned embedding already handles them, so char-tri became redundant and
// slightly REGRESSED TEST (rec@99 80.7→79.5). Removed. (Possible future re-test: it may still help
// SKUs with NO embedding vector — freshly scraped — where string similarity is the only fallback.)

// A distinctive token whose co-occurrence DEGREE-per-df (distinct catalog companions ÷ its
// own listing count) is below this is treated as an ENTITY (distillery — repeats the same
// few bottlers/casks); at or above it, a TRAIT/descriptor (oloroso/speyside/limited — broad,
// varied company). Empirically entities sit ≈0.6–1.0 and traits ≈1.3+; 1.1 is the gap and
// gives the best held-out result. See crossEntityConflicts in extractBlendFeatures.
export const ENTITY_DEGPERDF_MAX = 1.1;
// A conflicting token must appear in at least this many listings to count as WELL-ATTESTED
// (so a one-off idiosyncratic token like a df=1 mis-spelling can't manufacture a conflict).
export const WELL_ATTESTED_DF_MIN = 20;

// Two tokens that are one edit apart (gran↔grand) or a near-prefix (john↔johnnie) are the
// same identity misspelled/abbreviated — messy-data variants, NOT a real entity conflict.
// Used to exclude them from the crossEntityConflicts count.
function fuzzyVariant(x, y) {
	if (Math.abs(x.length - y.length) <= 1 && levenshtein(x, y) <= 1) return true;
	const mn = Math.min(x.length, y.length);
	const mx = Math.max(x.length, y.length);
	return mx > 0 && (x.startsWith(y) || y.startsWith(x)) && mn / mx >= 0.8;
}

function isBadSkuLite(sku) {
	const s = String(sku || "").toLowerCase();
	if (!s) return true;
	return s.startsWith("u:") || s.startsWith("id:") || s.startsWith("upc:") || s === "unknown";
}

// ctx = prepScorePairCtx(anchor); candidate = the aggregate being scored.
// opts = { vocab, sizePenaltyFn, pricePenaltyFn, detScore, embedCosFn? }
export function extractBlendFeatures(ctx, candidate, opts) {
	const vocab = opts.vocab;
	const nameA = ctx.name || "";
	const nameB = candidate.name || "";
	const aSku = String(ctx.sku || "");
	const bSku = String(candidate.sku || "");

	const normB = normSearchText(nameB);
	const rawB = tokenizeQuery(normB);
	const fB = filterSimTokens(rawB);
	const fA = ctx.toks || [];
	const setA = new Set(fA);
	const setB = new Set(fB);

	let sharedTok = 0;
	for (const t of setA) if (setB.has(t)) sharedTok++;
	const unionTok = new Set([...setA, ...setB]).size || 1;

	const contain = tokenContainmentScore(ctx.rawToks, rawB);
	const wo = vocab.weightedOverlap(nameA, nameB);

	const distA = ctx.distinctiveTerms || new Set();
	const distB = vocab.distinctiveUnigramsForName(nameB) || new Set();
	const termsA = vocab.termsForName(nameA);
	const termsB = vocab.termsForName(nameB);

	let covM = 0;
	for (const t of distA) if (termsB.has(t)) covM++;
	const tgtCov = distA.size ? covM / distA.size : 1;
	let candExtra = 0;
	for (const t of distB) if (!termsA.has(t)) candExtra++;

	// crossEntityConflicts — the independent-bottler discriminator (token co-occurrence
	// structure at the catalog level). It COUNTS the unshared-distinctive cross-pairs
	// (x in A-only, y in B-only) that are mutually-exclusive ENTITIES: co-occur NEVER, are
	// each WELL-ATTESTED (df ≥ WELL_ATTESTED_DF_MIN), are each ENTITY-LIKE (low degPerDf, see
	// below), and are NOT fuzzy spelling-variants of each other. Cadenhead Benriach↔Jura
	// counts 2 (benriach×jura, glenlivet×jura) → REJECT; a true alias counts 0 (idiosyncratic/
	// rare token, OR the brands DO co-occur somewhere, OR the "conflict" is a misspelling).
	//
	// Three gates, each measured, each necessary:
	//  • never-co-occur alone is useless — it also describes ~75% of true semantic-gap positives.
	//  • the ENTITY gate is the key insight (graph-structural, DISCOVERED not hardcoded): a trait
	//    like `oloroso` co-occurs with a broad, unrelated range of products → high degree-per-df
	//    (≈1.6 distinct companions per listing); a distillery repeats the same few bottlers/casks
	//    → low degree-per-df (≈0.75). Gating both tokens to degPerDf < ENTITY_DEGPERDF_MAX is what
	//    separates a distillery (jura) from a DESCRIPTOR (speyside/oloroso/original) — both are
	//    well-attested and never co-occur with the other side, so df alone can't tell them apart.
	//  • the FUZZY gate drops messy-data variants (gran↔grand, john↔johnnie) that look like
	//    conflicts but are one identity misspelled.
	// Together: ~99.6% precision-as-negative on the labeled set (vs ~96% df-only), and the best
	// held-out rec@99 — while sparing Tomintoul Speyside↔Oloroso and the semantic-gap aliases.
	const dfFn = typeof vocab.dfOf === "function" ? vocab.dfOf : () => 0;
	// degree-per-df: a node's distinct co-occurrence partners ÷ its listings. Low → entity
	// (same company repeats), high → trait/descriptor (broad, varied company). A
	// non-distinctive / graphless token is treated as trait-like (Infinity → never counts a
	// conflict) so the feature only ever fires on confident entity-vs-entity conflicts.
	const degPerDf = (t) => {
		const m = vocab.coocSet && vocab.coocSet(t);
		const d = dfFn(t);
		return m && d ? m.size / d : Infinity;
	};
	let entityConflicts = 0;
	if (typeof vocab.coocCount === "function") {
		for (const x of distA) {
			if (termsB.has(x)) continue; // shared term → not a conflicting identity token
			if (dfFn(x) < WELL_ATTESTED_DF_MIN || degPerDf(x) >= ENTITY_DEGPERDF_MAX) continue;
			for (const y of distB) {
				if (termsA.has(y)) continue;
				if (dfFn(y) < WELL_ATTESTED_DF_MIN || degPerDf(y) >= ENTITY_DEGPERDF_MAX) continue;
				if (vocab.coocCount(x, y) === 0 && !fuzzyVariant(x, y)) entityConflicts++;
			}
		}
	}

	const uniA = ctx.allUnigrams || new Set();
	let interW = 0;
	let totalW = 0;
	for (const t of uniA) {
		const w = vocab.idf(t);
		totalW += w;
		if (termsB.has(t)) interW += w;
	}
	const gradedCov = totalW > 0 ? interW / totalW : 1;

	const topTerm = ctx.topTerm;
	const topTermShared = topTerm && topTerm.idf >= DISTINCTIVE_IDF && termsB.has(topTerm.term) ? 1 : 0;

	const sizePen = typeof opts.sizePenaltyFn === "function" ? opts.sizePenaltyFn(aSku, bSku) : 1;
	const pricePen = typeof opts.pricePenaltyFn === "function" ? opts.pricePenaltyFn(aSku, bSku) : 1;

	const ageA = ctx.age || "";
	const ageB = extractAgeFromText(normB);
	let ageRel = 0;
	if (ageA && ageB) ageRel = ageA === ageB ? 1 : -1;
	else if (ageA && !ageB && bareAgeCandidates(normB).has(ageA)) ageRel = 1;
	else if (ageB && !ageA && bareAgeCandidates(ctx.norm || "").has(ageB)) ageRel = 1;
	const ageOneSided = (ageA && !ageB) || (ageB && !ageA) ? 1 : 0;

	const abvA = ctx.abv;
	const abvB = extractAbv(normB);
	const abvMult = abvMultiplier(abvA, abvB);
	const abvBoth = abvA != null && abvB != null ? 1 : 0;

	const edA = ctx.editionCodes || new Set();
	const edB = extractEditionCodes(nameB) || new Set();
	const edMult = editionCodeMultiplier(edA, edB);
	let smwsShared = 0;
	for (const c of edA)
		if (c.startsWith("smws:") && edB.has(c)) {
			smwsShared = 1;
			break;
		}
	const edBoth = edA.size > 0 && edB.size > 0 ? 1 : 0;

	const conceptMult = conceptConflictMultiplier(nameA, nameB);

	// containGated — GATED distinctive-token containment. The RAW
	// `shorterDistinctiveContain` (fraction of the shorter name's distinctive idf≥3 tokens
	// present in the longer name; same computation as tools/linker_ml/other_pattern.mjs)
	// is a strong RECALL signal for diluted same-product variants, but on its own it
	// REGRESSED the 99%-precision tail (84.5→81-84): same-distillery/different-EXPRESSION
	// negatives (in `ignores`) share the high-idf distillery token and have equally high
	// containment, so the raw feature pulled them over the auto-link line. The fix: multiply
	// containment by a NO-CONFLICT gate so it only fires for pairs with no conflicting
	// edition/age/abv/size — i.e. the crowding negatives (which differ on exactly those
	// attributes) get 0, only genuine same-product variants keep the signal.
	//   gate=1 iff edMult>=0.9 (no edition-code conflict: conflict→0.1)
	//          AND abvMult>=0.9 (no abv conflict: ≥1.5 apart → ≤0.4)
	//          AND sizePen>=0.9 (no size conflict: different format → 0.08, inferred → 0.3/0.7)
	//          AND ageRel !== -1 (no two-sided age conflict; one-sided age is allowed).
	// idf threshold uses vocab.idf(t) = ln((N+1)/(df(t)+1)) directly (identical to the offline
	// reference, no separate N needed); the shorter name is the one with fewer filtered tokens.
	const [shortToks, longSet] = fA.length <= fB.length ? [fA, setB] : [fB, setA];
	const shortDist = shortToks.filter((t) => vocab.idf(t) >= 3);
	const shorterDistinctiveContain = shortDist.length
		? shortDist.filter((t) => longSet.has(t)).length / shortDist.length
		: 0;
	const noConflictGate =
		edMult >= 0.9 && abvMult >= 0.9 && sizePen >= 0.9 && ageRel !== -1 ? 1 : 0;
	const containGated = shorterDistinctiveContain * noConflictGate;

	const aStores = ctx.stores instanceof Set ? ctx.stores : new Set(ctx.stores || []);
	const bStores = candidate.stores;
	const bHas = bStores
		? typeof bStores.has === "function"
			? (x) => bStores.has(x)
			: (x) => bStores.includes(x)
		: () => false;
	let storeShared = 0;
	for (const s of aStores)
		if (bHas(s)) {
			storeShared = 1;
			break;
		}

	const badSku = isBadSkuLite(aSku) || isBadSkuLite(bSku) ? 1 : 0;
	const detScore = Number.isFinite(opts.detScore) ? opts.detScore : 0;
	const embedCos = typeof opts.embedCosFn === "function" ? opts.embedCosFn(aSku, bSku) : 0;

	// Group-wise signals (canonical-GROUP, not pairwise). Computed by the caller and
	// passed in (offline: featurize.mjs via honest edge-cut; live: from the current
	// canonical map). Default 0 (neutral) when the caller doesn't supply them.
	//   grpStoreOverlap — fraction of stores where the two GROUPS carry DIFFERENT,
	//     non-upgrade SKUs (a store rarely lists the same product twice → evidence the
	//     groups are different products). Small by nature (0, ~0.1, ~0.3).
	//   grpSizeConflict — 1 when the two groups' resolved bottle sizes are disjoint.
	const grpStoreOverlap = Number.isFinite(opts.grpStoreOverlap) ? opts.grpStoreOverlap : 0;
	const grpSizeConflict = Number.isFinite(opts.grpSizeConflict) ? opts.grpSizeConflict : 0;

	return {
		logDet: Math.log1p(Math.max(0, detScore)),
		contain,
		woScore: wo.score,
		woShared: (wo.shared && wo.shared.length) || 0,
		topTermShared,
		tgtCov,
		candExtra,
		gradedCov,
		sizePen,
		pricePen,
		ageRel,
		ageOneSided,
		abvMult,
		abvBoth,
		edMult,
		edBoth,
		smwsShared,
		conceptMult,
		storeShared,
		badSku,
		sharedTok,
		jacc: sharedTok / unionTok,
		minTok: Math.min(fA.length, fB.length),
		maxTok: Math.max(fA.length, fB.length),
		lenDiff: Math.abs((ctx.norm || "").length - normB.length),
		containGated,
		grpStoreOverlap,
		grpSizeConflict,
		crossEntityConflicts: entityConflicts,
		embedCos,
	};
}

// Map an unbounded classical match score (0→∞) to a 0–1 confidence for display, so the
// AI-off (raw scorer) and AI-on (calibrated probability) modes share ONE scale. Monotonic
// (s/(s+1)) → preserves the exact ranking and the sharp separation: 29→0.97, 2→0.67, 0.2→0.17.
export const toConfidence01 = (s) => (s > 0 ? s / (s + 1) : 0);

const sigmoid = (z) => (z >= 0 ? 1 / (1 + Math.exp(-z)) : Math.exp(z) / (1 + Math.exp(z)));

// weights = { keys, mean, std, w, b }. Returns a calibrated probability in [0,1].
// A non-finite feature (e.g. embed_cosine for a SKU with no vector) contributes NOTHING
// (neutral), rather than being read as 0 — a real cosine of 0 means "dissimilar", which
// would wrongly crush the score. Missing ≠ dissimilar.
export function blendScore(features, weights) {
	if (!weights || !weights.keys) return 0;
	let dot = weights.b;
	for (let j = 0; j < weights.keys.length; j++) {
		const v = Number(features[weights.keys[j]]);
		if (!Number.isFinite(v)) continue; // missing feature → neutral
		dot += weights.w[j] * ((v - weights.mean[j]) / (weights.std[j] || 1));
	}
	return sigmoid(dot);
}
