// Generated by tools/mine_sku_aliases.mjs — do not edit by hand.
// Rows are undirected; buildAliasTable() expands both directions.
// Regenerate with: node tools/mine_sku_aliases.mjs
export const SKU_ALIASES = [
	["reserva", "reserve"],
	["barrel", "barrell"],
	["bourbo", "bourbon"],
	["brother", "brothers"],
	["distiller", "distillers"],
	["maker", "makers"],
	["michter", "michters"],
	["abunadh", "bunadh"],
	["edition", "editions"],
	["founder", "founders"],
	["grant", "grants"],
	["heaven", "heavens"],
	["may", "mays"],
	["pusser", "pussers"],
	["symington", "symingtons"],
	["admiral", "admirals"],
	["archive", "archives"],
	["batc", "batch"],
	["bell", "bells"],
	["castaway", "castaways"],
	["dillon", "dillons"],
	["driver", "drivers"],
	["etude", "etudes"],
	["exclusiva", "exclusive"],
	["farmer", "farmers"],
	["jefferson", "jeffersons"],
	["kracken", "kraken"],
	["leiper", "leipers"],
	["maclean", "macleans"],
	["masterson", "mastersons"],
	["roper", "ropers"],
	["russell", "russells"],
];

export function buildAliasTable() {
	const m = new Map();
	for (const [s, t] of SKU_ALIASES) {
		let a = m.get(s);
		if (!a) m.set(s, (a = []));
		a.push(t);
		a = m.get(t);
		if (!a) m.set(t, (a = []));
		a.push(s);
	}
	return m;
}
