#!/usr/bin/env node
/**
 * tools/linker_ml/make_blend_weights.mjs — generate the SHIPPED blend weights.
 *
 * Trains the logistic-regression blend on the FULL labeled set (no held-out split — this
 * is the production artifact, not the eval) and writes two weight sets to
 * viz/app/linker_page/blend_weights.js (committed on main):
 *   BLEND_WEIGHTS_EMBED   — includes embed_cosine; use when a vectors file is loaded.
 *   BLEND_WEIGHTS_NOEMBED — drops embed_cosine; correct calibration without embeddings.
 *
 * Run AFTER dump_features.mjs (so out/features.jsonl reflects the current embeddings).
 * Run:  node tools/linker_ml/make_blend_weights.mjs
 */

import fs from "fs";
import path from "path";
import { OUT_DIR, ROOT, FEATURE_KEYS } from "./featurize.mjs";

const rows = fs
	.readFileSync(path.join(OUT_DIR, "features.jsonl"), "utf8")
	.split("\n")
	.filter(Boolean)
	.map((l) => JSON.parse(l));

const sigmoid = (z) => (z >= 0 ? 1 / (1 + Math.exp(-z)) : Math.exp(z) / (1 + Math.exp(z)));

// Balanced, L2-regularized logistic regression on standardized features, full-batch GD.
function trainLR(data, keys, { epochs = 3000, lr = 0.5, l2 = 1e-4 } = {}) {
	const D = keys.length;
	const X = data.map((r) => keys.map((k) => (Number.isFinite(Number(r[k])) ? Number(r[k]) : 0)));
	const y = data.map((r) => r.label);
	const mean = new Array(D).fill(0);
	const std = new Array(D).fill(0);
	for (const x of X) for (let j = 0; j < D; j++) mean[j] += x[j];
	for (let j = 0; j < D; j++) mean[j] /= X.length;
	for (const x of X) for (let j = 0; j < D; j++) std[j] += (x[j] - mean[j]) ** 2;
	for (let j = 0; j < D; j++) std[j] = Math.sqrt(std[j] / X.length) || 1;
	const Z = X.map((x) => x.map((v, j) => (v - mean[j]) / std[j]));

	const nPos = y.reduce((a, b) => a + b, 0);
	const nNeg = y.length - nPos;
	const wPos = y.length / (2 * nPos);
	const wNeg = y.length / (2 * nNeg);

	const w = new Array(D).fill(0);
	let b = 0;
	for (let ep = 0; ep < epochs; ep++) {
		const gw = new Array(D).fill(0);
		let gb = 0;
		let wsum = 0;
		for (let i = 0; i < Z.length; i++) {
			let dot = b;
			for (let j = 0; j < D; j++) dot += w[j] * Z[i][j];
			const p = sigmoid(dot);
			const cw = y[i] ? wPos : wNeg;
			const g = cw * (p - y[i]);
			for (let j = 0; j < D; j++) gw[j] += g * Z[i][j];
			gb += g;
			wsum += cw;
		}
		for (let j = 0; j < D; j++) w[j] -= lr * (gw[j] / wsum + l2 * w[j]);
		b -= lr * (gb / wsum);
	}
	const r6 = (x) => Math.round(x * 1e6) / 1e6;
	return { keys, mean: mean.map(r6), std: std.map(r6), w: w.map(r6), b: r6(b) };
}

const embedKeys = FEATURE_KEYS;
const noEmbedKeys = FEATURE_KEYS.filter((k) => k !== "embedCos");

console.log(`training EMBED weights on ${rows.length} rows (${embedKeys.length} features)…`);
const embed = trainLR(rows, embedKeys);
console.log(`training NOEMBED weights on ${rows.length} rows (${noEmbedKeys.length} features)…`);
const noembed = trainLR(rows, noEmbedKeys);

const header = `// AUTO-GENERATED by tools/linker_ml/make_blend_weights.mjs — DO NOT EDIT BY HAND.
// Logistic-regression blend over the deterministic SKU-match factors (+ embed_cosine),
// trained on the full labeled set. Standardized: prob = sigmoid(b + Σ wᵢ·(xᵢ-meanᵢ)/stdᵢ).
// Use BLEND_WEIGHTS_EMBED when a vectors file is loaded (viz/app/linker_page/embeddings.js),
// otherwise BLEND_WEIGHTS_NOEMBED (correct calibration without the embedding feature).
// Regenerate after retraining: node tools/linker_ml/make_blend_weights.mjs
`;
const out =
	header +
	`export const BLEND_WEIGHTS_EMBED = ${JSON.stringify(embed)};\n` +
	`export const BLEND_WEIGHTS_NOEMBED = ${JSON.stringify(noembed)};\n`;

const dest = path.join(ROOT, "viz/app/linker_page/blend_weights.js");
fs.writeFileSync(dest, out);
console.log(`wrote ${path.relative(ROOT, dest)} (${out.length} bytes)`);
