"use strict";

const fs = require("fs");
const path = require("path");

const { normalizeImplicitSkuKey } = require("../utils/sku_canonical");
const { storeIdFromDbPath } = require("../utils/sku_collisions");

// Auto-generated SKU links — distinct from the manually curated data/sku_links.json.
// Generated by merge.js when pickBetterSku() upgrades a record's SKU in place
// (e.g., u:URL-hash -> real numeric SKU after a hydration pass).
//
// Schema (intentionally mirrors data/sku_links.json so consumers can union the
// .links arrays without special-casing):
//   {
//     "generatedAt": "<ISO>",
//     "source": "auto:sku-upgrade",
//     "links": [
//       { "fromSku": "u:abc", "toSku": "473058", "ts": "<ISO>", "url": "...", "dbFile": "..." }
//     ]
//   }

function pairKey(a, b) {
	const x = normalizeImplicitSkuKey(a);
	const y = normalizeImplicitSkuKey(b);
	if (!x || !y) return "";
	return x < y ? `${x}|${y}` : `${y}|${x}`;
}

function autoLinksPath(dbDir) {
	return path.join(dbDir, "..", "sku_links_auto.json");
}

// Missing file = no edges yet. An unparseable one must throw: the merge writes the result back, so
// reading it as empty would replace every recorded upgrade with just this run's.
function readExisting(file) {
	if (!fs.existsSync(file)) return { links: [] };
	const obj = JSON.parse(fs.readFileSync(file, "utf8"));
	if (!Array.isArray(obj.links)) throw new Error(`${file}: expected {links:[]}`);
	return { links: obj.links };
}

// A pair a human or audit has ignored (data/sku_links.json) must never be re-joined by an upgrade:
// `tools/apply_audit_proposal.js` unlink-auto removes a wrong edge and writes that ignore.
function readIgnoredPairs(dbDir) {
	const file = path.join(dbDir, "..", "sku_links.json");
	if (!fs.existsSync(file)) return new Set();
	const obj = JSON.parse(fs.readFileSync(file, "utf8"));
	return new Set((obj.ignores || []).map((ig) => pairKey(ig.skuA, ig.skuB)));
}

function writeAtomic(file, obj) {
	const tmp = `${file}.tmp`;
	fs.writeFileSync(tmp, JSON.stringify(obj, null, 2) + "\n", "utf8");
	fs.renameSync(tmp, file);
}

// Merge new upgrades into sku_links_auto.json, and re-point existing edges onto collision splits
// (data/sku_collisions.json) on every run, so adding a split never needs a hand edit here.
// `splits` = loadCollisionSplits(<dbDir>/..). Idempotent: one entry per unordered (fromSku, toSku) pair.
// First-seen wins.
function mergeUpgradesIntoAutoLinks({ dbDir, upgrades, splits }) {
	if (!Array.isArray(upgrades)) throw new Error("mergeUpgradesIntoAutoLinks: upgrades must be an array");

	const file = autoLinksPath(dbDir);
	const { links: existing } = readExisting(file);

	// Both ends: fromSku is usually u:, but an upgrade can start from a real number (id: -> CSPC).
	let repointed = 0;
	for (const l of existing) {
		if (!l.dbFile || !l.url) continue;
		const storeId = storeIdFromDbPath(l.dbFile);
		const from = splits.resolve(storeId, l.fromSku, l.url);
		const to = splits.resolve(storeId, l.toSku, l.url);
		if (from !== l.fromSku || to !== l.toSku) {
			l.fromSku = from;
			l.toSku = to;
			repointed++;
		}
	}

	const byPair = new Map();
	for (const l of existing) {
		const k = pairKey(l?.fromSku, l?.toSku);
		if (k && !byPair.has(k)) byPair.set(k, l);
	}

	const ignored = readIgnoredPairs(dbDir);
	let added = 0;
	for (const u of upgrades) {
		if (!u.dbFile) throw new Error(`sku upgrade ${u.fromSku} -> ${u.toSku} has no dbFile`);
		const storeId = storeIdFromDbPath(u.dbFile);
		const fromSku = splits.resolve(storeId, normalizeImplicitSkuKey(u.fromSku), u.url);
		const toSku = splits.resolve(storeId, normalizeImplicitSkuKey(u.toSku), u.url);
		const k = pairKey(fromSku, toSku);
		if (!k) continue;
		if (byPair.has(k) || ignored.has(k)) continue;
		byPair.set(k, {
			fromSku,
			toSku,
			ts: u.ts || new Date().toISOString(),
			url: u.url || "",
			dbFile: u.dbFile || "",
		});
		added++;
	}

	if (added === 0 && repointed === 0) return { added: 0, repointed: 0, total: byPair.size, file };

	const links = Array.from(byPair.values()).sort((a, b) => {
		const ka = pairKey(a.fromSku, a.toSku);
		const kb = pairKey(b.fromSku, b.toSku);
		return ka < kb ? -1 : ka > kb ? 1 : 0;
	});

	writeAtomic(file, {
		generatedAt: new Date().toISOString(),
		source: "auto:sku-upgrade",
		links,
	});

	return { added, repointed, total: links.length, file };
}

module.exports = { mergeUpgradesIntoAutoLinks, autoLinksPath, pairKey };
