"use strict";

const fs = require("fs");
const path = require("path");

const { normalizeImplicitSkuKey } = require("../utils/sku_canonical");

// Auto-generated SKU links — distinct from the manually curated data/sku_links.json.
// Generated by merge.js when pickBetterSku() upgrades a record's SKU in place
// (e.g., u:URL-hash -> real numeric SKU after a hydration pass).
//
// Schema (intentionally mirrors data/sku_links.json so consumers can union the
// .links arrays without special-casing):
//   {
//     "generatedAt": "<ISO>",
//     "source": "auto:sku-upgrade",
//     "links": [
//       { "fromSku": "u:abc", "toSku": "473058", "ts": "<ISO>", "url": "...", "dbFile": "..." }
//     ]
//   }

function pairKey(a, b) {
	const x = normalizeImplicitSkuKey(a);
	const y = normalizeImplicitSkuKey(b);
	if (!x || !y) return "";
	return x < y ? `${x}|${y}` : `${y}|${x}`;
}

function autoLinksPath(dbDir) {
	return path.join(dbDir, "..", "sku_links_auto.json");
}

function readExisting(file) {
	try {
		const txt = fs.readFileSync(file, "utf8");
		const obj = JSON.parse(txt);
		const links = Array.isArray(obj?.links) ? obj.links : [];
		return { ok: true, obj, links };
	} catch {
		return { ok: false, obj: null, links: [] };
	}
}

function writeAtomic(file, obj) {
	const tmp = `${file}.tmp`;
	fs.writeFileSync(tmp, JSON.stringify(obj, null, 2) + "\n", "utf8");
	fs.renameSync(tmp, file);
}

// Merge new upgrades into sku_links_auto.json.
// Idempotent: one entry per unordered (fromSku, toSku) pair. First-seen wins.
function mergeUpgradesIntoAutoLinks({ dbDir, upgrades }) {
	if (!Array.isArray(upgrades) || upgrades.length === 0) {
		return { added: 0, total: 0, file: autoLinksPath(dbDir) };
	}

	const file = autoLinksPath(dbDir);
	const { links: existing } = readExisting(file);

	const byPair = new Map();
	for (const l of existing) {
		const k = pairKey(l?.fromSku, l?.toSku);
		if (k && !byPair.has(k)) byPair.set(k, l);
	}

	let added = 0;
	for (const u of upgrades) {
		const fromSku = normalizeImplicitSkuKey(u.fromSku);
		const toSku = normalizeImplicitSkuKey(u.toSku);
		const k = pairKey(fromSku, toSku);
		if (!k) continue;
		if (byPair.has(k)) continue;
		byPair.set(k, {
			fromSku,
			toSku,
			ts: u.ts || new Date().toISOString(),
			url: u.url || "",
			dbFile: u.dbFile || "",
		});
		added++;
	}

	if (added === 0) return { added: 0, total: byPair.size, file };

	const links = Array.from(byPair.values()).sort((a, b) => {
		const ka = pairKey(a.fromSku, a.toSku);
		const kb = pairKey(b.fromSku, b.toSku);
		return ka < kb ? -1 : ka > kb ? 1 : 0;
	});

	writeAtomic(file, {
		generatedAt: new Date().toISOString(),
		source: "auto:sku-upgrade",
		links,
	});

	return { added, total: links.length, file };
}

module.exports = { mergeUpgradesIntoAutoLinks, autoLinksPath, pairKey };
